// ==========================================
// SEO ENHANCEMENT MODULE
// ==========================================

// ==========================================
// SEO FORM IN PRODUCT MODAL
// ==========================================

function addSEOFieldsToProductForm() {
    const form = document.getElementById('product-form');
    if (!form) return;

    // Add SEO section after main fields
    const seoSection = `
        <div class="form-section seo-section">
            <h3 class="section-title">SEO Settings</h3>
            <p class="section-description">Optimize your product for search engines</p>
            
            <div class="form-group">
                <label>SEO Title (Meta Title)</label>
                <input type="text" id="product-meta-title" maxlength="60" placeholder="Leave empty to use product name">
                <small class="char-count"><span id="meta-title-count">0</span>/60 characters</small>
            </div>
            
            <div class="form-group">
                <label>Meta Description</label>
                <textarea id="product-meta-description" rows="3" maxlength="160" placeholder="Brief description for search results"></textarea>
                <small class="char-count"><span id="meta-desc-count">0</span>/160 characters</small>
            </div>
            
            <div class="form-group">
                <label>URL Slug</label>
                <input type="text" id="product-slug" placeholder="auto-generated-from-name">
                <small>Used in product URL: /product/<strong id="slug-preview">example-shirt</strong></small>
            </div>
            
            <div class="form-group">
                <label>Keywords (comma-separated)</label>
                <input type="text" id="product-keywords" placeholder="shirt, casual, cotton">
                <small>Help search engines understand your product</small>
            </div>
            
            <div class="seo-score-card">
                <h4>SEO Score</h4>
                <div class="score-circle">
                    <span class="score-value" id="seo-score">0</span>
                    <span class="score-label">/100</span>
                </div>
                <div class="seo-checklist" id="seo-checklist">
                    <!-- Dynamic checklist will appear here -->
                </div>
            </div>
        </div>
    `;

    // Insert before form actions
    const formActions = form.querySelector('.form-actions');
    if (formActions) {
        formActions.insertAdjacentHTML('beforebegin', seoSection);
        initializeSEOListeners();
    }
}

function initializeSEOListeners() {
    // Character counters
    const metaTitle = document.getElementById('product-meta-title');
    const metaDesc = document.getElementById('product-meta-description');
    const slug = document.getElementById('product-slug');
    const productName = document.getElementById('product-name');

    if (metaTitle) {
        metaTitle.addEventListener('input', () => {
            document.getElementById('meta-title-count').textContent = metaTitle.value.length;
            calculateSEOScore();
        });
    }

    if (metaDesc) {
        metaDesc.addEventListener('input', () => {
            document.getElementById('meta-desc-count').textContent = metaDesc.value.length;
            calculateSEOScore();
        });
    }

    // Auto-generate slug from product name
    if (productName && slug) {
        productName.addEventListener('input', () => {
            if (!slug.value || slug.dataset.autoGenerated === 'true') {
                const generatedSlug = generateSlug(productName.value);
                slug.value = generatedSlug;
                slug.dataset.autoGenerated = 'true';
                document.getElementById('slug-preview').textContent = generatedSlug || 'example-shirt';
            }
            calculateSEOScore();
        });

        slug.addEventListener('input', () => {
            slug.dataset.autoGenerated = 'false';
            slug.value = generateSlug(slug.value);
            document.getElementById('slug-preview').textContent = slug.value || 'example-shirt';
            calculateSEOScore();
        });
    }

    // Recalculate SEO score on any field change
    const allInputs = document.querySelectorAll('#product-form input, #product-form textarea');
    allInputs.forEach(input => {
        input.addEventListener('input', () => calculateSEOScore());
    });
}

function generateSlug(text) {
    return text
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, '')
        .replace(/[\s_-]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

function calculateSEOScore() {
    const checks = {
        hasName: {
            check: () => document.getElementById('product-name')?.value.length > 0,
            label: 'Product name provided',
            points: 15
        },
        hasDescription: {
            check: () => document.getElementById('product-description')?.value.length >= 100,
            label: 'Description is detailed (100+ chars)',
            points: 15
        },
        hasMetaTitle: {
            check: () => {
                const title = document.getElementById('product-meta-title')?.value;
                return title && title.length >= 30 && title.length <= 60;
            },
            label: 'SEO title is optimal (30-60 chars)',
            points: 20
        },
        hasMetaDescription: {
            check: () => {
                const desc = document.getElementById('product-meta-description')?.value;
                return desc && desc.length >= 120 && desc.length <= 160;
            },
            label: 'Meta description is optimal (120-160 chars)',
            points: 20
        },
        hasSlug: {
            check: () => document.getElementById('product-slug')?.value.length > 0,
            label: 'URL slug is set',
            points: 10
        },
        hasKeywords: {
            check: () => {
                const keywords = document.getElementById('product-keywords')?.value;
                return keywords && keywords.split(',').filter(k => k.trim()).length >= 3;
            },
            label: 'Has 3+ keywords',
            points: 10
        },
        hasImage: {
            check: () => document.getElementById('product-image')?.value.length > 0,
            label: 'Product image provided',
            points: 10
        }
    };

    let totalScore = 0;
    let checklistHTML = '<ul class="checklist">';

    for (const [key, item] of Object.entries(checks)) {
        const passed = item.check();
        if (passed) totalScore += item.points;
        
        checklistHTML += `
            <li class="${passed ? 'passed' : 'failed'}">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    ${passed 
                        ? '<path d="M20 6L9 17l-5-5" stroke-width="2" stroke-linecap="round"/>'
                        : '<path d="M18 6L6 18M6 6l12 12" stroke-width="2" stroke-linecap="round"/>'
                    }
                </svg>
                <span>${item.label}</span>
            </li>
        `;
    }

    checklistHTML += '</ul>';

    // Update score display
    const scoreEl = document.getElementById('seo-score');
    const checklistEl = document.getElementById('seo-checklist');

    if (scoreEl) {
        scoreEl.textContent = totalScore;
        scoreEl.className = 'score-value ' + getScoreClass(totalScore);
    }

    if (checklistEl) {
        checklistEl.innerHTML = checklistHTML;
    }

    return totalScore;
}

function getScoreClass(score) {
    if (score >= 80) return 'excellent';
    if (score >= 60) return 'good';
    if (score >= 40) return 'fair';
    return 'poor';
}

// ==========================================
// SAVE SEO DATA WITH PRODUCT
// ==========================================

function getSEOFormData() {
    return {
        meta_title: document.getElementById('product-meta-title')?.value || null,
        meta_description: document.getElementById('product-meta-description')?.value || null,
        slug: document.getElementById('product-slug')?.value || null,
        keywords: document.getElementById('product-keywords')?.value.split(',').map(k => k.trim()).filter(Boolean) || [],
        seo_score: parseInt(document.getElementById('seo-score')?.textContent) || 0
    };
}

function populateSEOForm(product) {
    if (!product) return;

    const metaTitle = document.getElementById('product-meta-title');
    const metaDesc = document.getElementById('product-meta-description');
    const slug = document.getElementById('product-slug');
    const keywords = document.getElementById('product-keywords');

    if (metaTitle) metaTitle.value = product.meta_title || '';
    if (metaDesc) metaDesc.value = product.meta_description || '';
    if (slug) {
        slug.value = product.slug || generateSlug(product.name);
        slug.dataset.autoGenerated = product.slug ? 'false' : 'true';
    }
    if (keywords) keywords.value = product.keywords?.join(', ') || '';

    // Update character counts
    if (metaTitle) document.getElementById('meta-title-count').textContent = metaTitle.value.length;
    if (metaDesc) document.getElementById('meta-desc-count').textContent = metaDesc.value.length;

    // Calculate initial SEO score
    calculateSEOScore();
}

// ==========================================
// GENERATE SITEMAP
// ==========================================

async function generateSitemap() {
    try {
        const { data: products, error } = await supabase
            .from('products')
            .select('slug, name, updated_at')
            .order('updated_at', { ascending: false });

        if (error) throw error;

        const baseURL = window.location.origin;
        const today = new Date().toISOString().split('T')[0];

        let sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n';
        sitemap += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

        // Homepage
        sitemap += `  <url>\n`;
        sitemap += `    <loc>${baseURL}/</loc>\n`;
        sitemap += `    <lastmod>${today}</lastmod>\n`;
        sitemap += `    <changefreq>daily</changefreq>\n`;
        sitemap += `    <priority>1.0</priority>\n`;
        sitemap += `  </url>\n`;

        // Product pages
        products?.forEach(product => {
            const slug = product.slug || generateSlug(product.name);
            const lastmod = new Date(product.updated_at).toISOString().split('T')[0];
            
            sitemap += `  <url>\n`;
            sitemap += `    <loc>${baseURL}/product/${slug}</loc>\n`;
            sitemap += `    <lastmod>${lastmod}</lastmod>\n`;
            sitemap += `    <changefreq>weekly</changefreq>\n`;
            sitemap += `    <priority>0.8</priority>\n`;
            sitemap += `  </url>\n`;
        });

        // Static pages
        const staticPages = [
            { path: '/about', priority: '0.7', changefreq: 'monthly' },
            { path: '/contact', priority: '0.6', changefreq: 'monthly' }
        ];

        staticPages.forEach(page => {
            sitemap += `  <url>\n`;
            sitemap += `    <loc>${baseURL}${page.path}</loc>\n`;
            sitemap += `    <lastmod>${today}</lastmod>\n`;
            sitemap += `    <changefreq>${page.changefreq}</changefreq>\n`;
            sitemap += `    <priority>${page.priority}</priority>\n`;
            sitemap += `  </url>\n`;
        });

        sitemap += '</urlset>';

        // Download sitemap
        const blob = new Blob([sitemap], { type: 'application/xml' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'sitemap.xml';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);

        showToast('Sitemap generated successfully!', 'success');
    } catch (error) {
        console.error('Error generating sitemap:', error);
        showToast('Failed to generate sitemap', 'error');
    }
}

// ==========================================
// ROBOTS.TXT GENERATOR
// ==========================================

function generateRobotsTxt() {
    const baseURL = window.location.origin;
    
    const robotsTxt = `# THREADLINE Robots.txt
User-agent: *
Allow: /
Disallow: /admin
Disallow: /api/
Disallow: /cart
Disallow: /checkout

# Sitemaps
Sitemap: ${baseURL}/sitemap.xml

# Crawl-delay
Crawl-delay: 1
`;

    const blob = new Blob([robotsTxt], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    showToast('robots.txt generated successfully!', 'success');
}

// ==========================================
// SCHEMA.ORG PRODUCT MARKUP
// ==========================================

function generateProductSchema(product) {
    if (!product) return null;

    const schema = {
        "@context": "https://schema.org/",
        "@type": "Product",
        "name": product.name,
        "description": product.description,
        "image": product.image_url,
        "sku": product.sku,
        "brand": {
            "@type": "Brand",
            "name": "THREADLINE"
        },
        "offers": {
            "@type": "Offer",
            "url": `${window.location.origin}/product/${product.slug || generateSlug(product.name)}`,
            "priceCurrency": "USD",
            "price": product.price,
            "availability": product.stock > 0 ? "https://schema.org/InStock" : "https://schema.org/OutOfStock",
            "itemCondition": "https://schema.org/NewCondition"
        }
    };

    if (product.meta_description) {
        schema.description = product.meta_description;
    }

    return schema;
}

function injectProductSchema(product) {
    const schema = generateProductSchema(product);
    if (!schema) return;

    // Remove existing schema if present
    const existing = document.querySelector('script[type="application/ld+json"]');
    if (existing) existing.remove();

    // Inject new schema
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.textContent = JSON.stringify(schema);
    document.head.appendChild(script);
}

// ==========================================
// META TAGS INJECTION
// ==========================================

function updateMetaTags(product) {
    if (!product) return;

    const title = product.meta_title || `${product.name} | THREADLINE`;
    const description = product.meta_description || product.description.substring(0, 160);
    const imageUrl = product.image_url;
    const url = `${window.location.origin}/product/${product.slug || generateSlug(product.name)}`;

    // Update title
    document.title = title;

    // Update or create meta tags
    updateOrCreateMeta('description', description);
    updateOrCreateMeta('keywords', product.keywords?.join(', ') || '');

    // Open Graph tags
    updateOrCreateMeta('og:title', title, 'property');
    updateOrCreateMeta('og:description', description, 'property');
    updateOrCreateMeta('og:image', imageUrl, 'property');
    updateOrCreateMeta('og:url', url, 'property');
    updateOrCreateMeta('og:type', 'product', 'property');

    // Twitter Card tags
    updateOrCreateMeta('twitter:card', 'summary_large_image', 'name');
    updateOrCreateMeta('twitter:title', title, 'name');
    updateOrCreateMeta('twitter:description', description, 'name');
    updateOrCreateMeta('twitter:image', imageUrl, 'name');

    // Inject structured data
    injectProductSchema(product);
}

function updateOrCreateMeta(nameOrProperty, content, attribute = 'name') {
    let meta = document.querySelector(`meta[${attribute}="${nameOrProperty}"]`);
    
    if (!meta) {
        meta = document.createElement('meta');
        meta.setAttribute(attribute, nameOrProperty);
        document.head.appendChild(meta);
    }
    
    meta.setAttribute('content', content);
}

// ==========================================
// SEO SETTINGS PAGE IN ADMIN
// ==========================================

function createSEOSettingsPage() {
    const seoPageHTML = `
        <div class="page" id="seo-page">
            <div class="page-header">
                <h2>SEO Settings</h2>
                <p>Optimize your store for search engines</p>
            </div>

            <div class="settings-section">
                <h3>Site-wide SEO</h3>
                
                <div class="form-group">
                    <label>Site Title</label>
                    <input type="text" id="site-title" value="THREADLINE - Premium Shirts">
                </div>

                <div class="form-group">
                    <label>Site Description</label>
                    <textarea id="site-description" rows="3">Premium shirt collection for the modern individual</textarea>
                </div>

                <div class="form-group">
                    <label>Default Keywords</label>
                    <input type="text" id="site-keywords" value="shirts, fashion, premium clothing">
                </div>
            </div>

            <div class="settings-section">
                <h3>Tools & Utilities</h3>
                
                <div class="tools-grid">
                    <button class="tool-btn" onclick="generateSitemap()">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                            <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" stroke-width="2" stroke-linecap="round"/>
                        </svg>
                        Generate Sitemap
                    </button>

                    <button class="tool-btn" onclick="generateRobotsTxt()">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                            <rect x="8" y="2" width="8" height="4" stroke-width="2"/>
                            <rect x="4" y="8" width="16" height="12" stroke-width="2"/>
                            <path d="M9 13h2M13 13h2M9 17h6" stroke-width="2" stroke-linecap="round"/>
                        </svg>
                        Generate Robots.txt
                    </button>
                </div>
            </div>

            <div class="settings-section">
                <h3>Analytics Integration</h3>
                
                <div class="form-group">
                    <label>Google Analytics ID</label>
                    <input type="text" id="ga-id" placeholder="G-XXXXXXXXXX">
                </div>

                <div class="form-group">
                    <label>Facebook Pixel ID</label>
                    <input type="text" id="fb-pixel" placeholder="1234567890">
                </div>
            </div>
        </div>
    `;

    // Add to main content area (would need to be integrated properly)
    return seoPageHTML;
}
